language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm    
    - sh -e /etc/init.d/xvfb start
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.7
script:
    - source qt-5.7.env
    - (cd source/Flux-Application-Full; qmake; make)
  
