name: quickfluxproject
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Summary
description: |
  Description
grade: stable
confinement: strict

parts:
  main:
    plugin: dump
    source: ./app
    stage-packages:
    - libc6
    - libgl1-mesa-dev
    - xkb-data
    - libxcb-xkb1
    - fontconfig-config

