version: '3'
services:
  myproject_build_machine:
    command: bash -c "export PATH=/opt/Qt/5.9/gcc_64/bin:$PATH && export BUILD_DIR=/tmp && which qmake && cd /src && ./deployment/linux/create_snap.sh"
    build:
      context: .
      dockerfile: qt.docker
    volumes:
      - "../..:/src"

