version: '3'
services:
  myproject_build_machine:
    command: bash -c "export PATH=/opt/Qt/5.9/gcc_64/bin:$PATH; which qmake; cd /src; ./scripts/release-snap.sh"
    build:
      context: .
      dockerfile: qt.docker
    volumes:
      - "../..:/src"

