name: lanto
version: '1.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: An Intuitive Batch Photo Resizer
description: |
  Simply drag photos over to Lanto. They will be converted to the format you desired.
  With intuitive user interface and powerful functions, you don't need to learn anything
  in order to use this application.
grade: stable
confinement: strict

parts:
  main:
    plugin: dump
    source: ./app
    stage-packages:
    - libc6
    - libgl1-mesa-dev
    - xkb-data
    - libxcb-xkb1
    - fontconfig-config

apps:
  lanto:
    command: qt5-launch $SNAP/Lanto
    plugs: [x11, home, opengl, desktop, gsettings, removable-media]
    desktop: lanto.desktop
